# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com
language: node_js

node_js:
  - 10
  
install:
  - npm install --only=dev --unsafe-perm --production

script: 
 - npm view build
